name: Trigger s2-specs-update for downstream repos
on:
  push:
    paths:
      - "s2/**"
jobs:
  dispatch:
    strategy:
      matrix:
        repo:
          - "s2-streamstore/docs"
          - "s2-streamstore/s2"
          - "s2-streamstore/s2-sdk-typescript"
          - "s2-streamstore/s2-sdk-go"
          - "s2-streamstore/s2-sdk-python"
          - "s2-streamstore/s2-sdk-java"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_SECRET_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ matrix.repo }}
          event-type: s2-specs-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
